Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  tempdir: "/home/egg/temp/"
  copyright: TBI - 2014
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://kronos.tbi.univie.ac.at:3000"
  tempdir: "/scratch/egg/temp/"
  copyright: TBI - 2014

Staging:
  host: "*4" # any IPv4 host
  port: 9000
  approot: "http://ventax.tbi.univie.ac.at:9000"
  tempdir: "/mnt/storage/temp/AlienServer"
  copyright: TBI - 2014

Production:
  #approot: "http://www.example.com"
  <<: *defaults
